In [2]:
#TEST
import networkx as nx
import random
from collections import defaultdict
import matplotlib.pyplot as plt
import sys
from tabulate import tabulate
import numpy as np
  
# setting path
sys.path.append('../../')
%load_ext autoreload
%autoreload 2
from graph_creation import MY_homophilic_ba_graph, create_graph
from people.people_recommender import people_recommender
from people.people_recommender_metrics import intra_list_similarity

In [ ]:
#TEST
G = create_graph(20, [1], avg_friend = 3, hp_alpha=5, hp_beta=0)
colors = list(nx.get_node_attributes(G, 'opinion').values())
labels =  nx.get_node_attributes(G, 'opinion')
#print(tabulate([[key] + [np.round(val, 3)] for key, val in labels.items()], headers=["node label", "opinion value"]))
nx.draw(G, labels= dict([index for index in enumerate(labels)]), node_color=colors, font_color='darkturquoise', vmin=-1, vmax=1, cmap = plt.cm.get_cmap('magma'))
plt.show()
G = people_recommender(G, [18], 'topology_based')

colors = list(nx.get_node_attributes(G, 'opinion').values())
labels =  nx.get_node_attributes(G, 'opinion')
#print(tabulate([[key] + [np.round(val, 3)] for key, val in labels.items()], headers=["node label", "opinion value"]))
nx.draw(G, labels= dict([index for index in enumerate(labels)]), node_color=colors, font_color='darkturquoise', vmin=-1, vmax=1, cmap = plt.cm.get_cmap('magma'))
plt.show()

In [ ]:
#TEST
# Calls MY_homophilic_ba_graph
G = MY_homophilic_ba_graph(10, 9, 0, 0)
  
# Remapping opinions from [0, 100] to [-1, 1]
opinions = nx.get_node_attributes(G, 'opinion')
for curr_op in opinions:
    opinions[curr_op] = (opinions[curr_op] - 50) / 50

# Setting opinions as node attributes  
nx.set_node_attributes(G, opinions, 'opinion')
colors = list(nx.get_node_attributes(G, 'opinion').values())
labels =  nx.get_node_attributes(G, 'opinion')
nx.draw(G, labels= dict([index for index in enumerate(labels)]), node_color=colors, font_color='darkturquoise', vmin=-1, vmax=1, cmap = plt.cm.get_cmap('magma'))
plt.show()

In [ ]:
#TEST
import numpy as np
arr = [2,7,8]
prova = np.random.choice(arr, size=1, replace=False)
print(prova[0])

In [ ]:
G = create_graph(5, [1], avg_friend = 3, hp_alpha=5, hp_beta=0)
colors = list(nx.get_node_attributes(G, 'opinion').values())
labels =  nx.get_node_attributes(G, 'opinion')
#print(tabulate([[key] + [np.round(val, 3)] for key, val in labels.items()], headers=["node label", "opinion value"]))
nx.draw(G, labels= dict([index for index in enumerate(labels)]), node_color=colors, font_color='darkturquoise', vmin=-1, vmax=1, cmap = plt.cm.get_cmap('magma'))
plt.show()
matrice = nx.to_numpy_matrix(G)
print(matrice)
prova = np.linalg.matrix_power(matrice, 3)
print(prova)
print(prova[0])
prova1 = list(map(int, np.ravel(prova[0])))
print(prova1)
print([x for x in prova1 if x > 0 and x > 1])

In [ ]:
target = [1, 5, 0, 3, 6, 40, 0, 70]
indici_validi = [0, 2, 3, 5, 6, 7]
three_hop_not_friends = [ind for ind, x in enumerate(target) if x > 0 and ind in indici_validi]
print(three_hop_not_friends)

In [ ]:
import pandas as pd
df2 = pd.DataFrame(data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index=[4, 5, 6], columns=['a', 'b', 'c'])
print(df2)

d = pd.DataFrame(0, index=np.arange(len(data)), columns=feature_list)

In [3]:
G = nx.star_graph(6)
#opinions_list = [-1] * 7
#opinions = dict(zip(G.nodes(), opinions_list))
nx.set_node_attributes(G, {0: 1, 1: 1, 2: 1, 3: 1, 4: -1, 5: -1, 6: 0, 7: 0}, 'opinion')
#nx.set_node_attributes(G, {0: [1,2]}, 'people_recommended')
prova = nx.get_node_attributes(G, 'people_recommended')
print(prova)
intra_list_similarity(G)

{}


{}

In [ ]:
import recmetrics
d = {'col0': [0, 1, 1], 'col1': [0, 0, 0], 'col2': [1, 0, 0]}
df = pd.DataFrame(data=d, index = [2, 3, 7])
print(df)
dati = [2,3,7]
print(recmetrics.intra_list_similarity([dati], df))

In [20]:
from scipy import special
prova = special.softmax(np.array([2/(np.finfo(np.float64).tiny + np.finfo(np.float64).tiny), 2/(np.finfo(np.float64).tiny + np.finfo(np.float64).tiny), 1/(np.finfo(np.float64).tiny + np.finfo(np.float64).tiny)]))
print(prova)
print(2/np.finfo(np.float64).tiny+np.finfo(np.float64).tiny)
print(3/np.finfo(np.float64).tiny)
prova2 = special.softmax([3/0.000000001, 3/0.000000001, 1/0.000000001])
print(prova2)
print("##########")
prova3 = special.softmax([0.5, 1, 2])
print(prova3)
prova4 = special.softmax([-0.5, -1, -2])
print(prova4)
prova5 = special.softmax([2-0.5, 2-1, 2-2])
print(prova5)
prova6 = special.softmax([1.5, 1, 0])
print(prova6)

[1. 1. 0.]
8.98846567431158e+307
1.348269851146737e+308
[0.5 0.5 0. ]
##########
[0.14024438 0.2312239  0.62853172]
[0.54654939 0.33149896 0.12195165]
[0.54654939 0.33149896 0.12195165]
[0.54654939 0.33149896 0.12195165]


In [13]:
class SimulateEpochPeopleRecommenderError(Exception):
    """Raised when an error occurred in the simulate_epoch_people_recommender method"""
    pass

i = 2
if i == 2:
    raise SimulateEpochPeopleRecommenderError
else:
    print("prova")

SimulateEpochPeopleRecommenderError: 